
-- Active: 1662222019915@@127.0.0.1@3306@phpmyadmin
/*REFERENCIA DE //josejuansanchez.org/bd/ejercicios-consultas-sql/index.html*/

/*QUE ES SQL?
ES UN LENGUAJE ESPECIFICO DEL DOMINIO PARA ACCESOS DE SISTEMAS DE GESTION DE BASE DE DATOS 
RELACIONALES, QUE PERMITE ESPECIFICAR DIVERSOS TIPOS DE OPERACIONES DE CONSULTAS ESTRUCTURADAS

/*QUE ES UNA BASE DATOS?
ES UN LUGAR DONDE PODEMOS GUARDAR DATOS DE UNA FORMA ORDENADA


/* DDL = LENGUAJE DE DEFINICION DE DATOS [ESTRUCTURA DE DATOS]*/
   --- CREATE   CREAR DATOS
        -- CREAR USUARIO  
            CREATE USER FREDY @LOCALHOST IDENTIFIED BY "123456";
        -- CREATE DATABASE
           ***EJEMPLO ESTRUCTURA COMPLETA***
           -- DROP DATABASE IF EXISTS PROYECTO;
            CREATE DATABASE PROYECTO SET utf8mb4;
             USE PROYECTO;
        -- CREATE TABLE (relacionar tablas)(tabla de enlace)
           -- CREATE TABLE 
           ***EJEMPLO ESTRUCUTURA TABLA COMPLETA***
                CREATE TABLE fabricante (
                codigo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                nombre VARCHAR(100) NOT NULL
                );

                CREATE TABLE producto (
                codigo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                nombre VARCHAR(100) NOT NULL,
                precio DOUBLE NOT NULL,
                codigo_fabricante INT UNSIGNED NOT NULL,
                FOREIGN KEY (codigo_fabricante) REFERENCES fabricante(codigo)
                );

   --- DROP     BORRAR DATOS
        - DROP DATABASE  
            ***EJEMPLO SINTAXYS BORRAR BD ***
            DROP DATABASE NOMBRE_BD
        - DROP TABLE (consistencia-integridad)  
            ***EJEMPLO SINTAXYS BORRAR UNA TABLA***
             DROP TABLE NOMBRE_TABLA 
   --- ALTER    ALTERAR DATOS
        - ALTER TABLE - RENAME
            ***EJEMPLO DE SINTAXYS PARA RENOMBRAR*** 
            ALTER TABLE NOMBRE_ACTUAL RENAME NOMBRE_CAMBIAR; 
        - ALTER TABLE - CHANGE
            ***EJEMPLO DE SINTAXYS PARA MODIFICAR***
            ALTER TABLE NOMBRE_TABLA CHANGE NOMBRE_ACTUAL NOMBRE_QUIERO INT (11);
        - ALTER TABLE - ADD COLUMN
            ***EJEMPLO DE SINTAXYS PARA AÑADIR UNA COLUMNA***
             ALTER TABLE NOMBRE_TABLA ADD COLUMN (DIRECCION VARCHAR(10))    
        - ALTER TABLE - DROP 
            ***EJEMPLO DE SINTAXYS PARA BORRAR UNA COLUMNA***
             ALTER TABLE NOMBRE_TABLA DROP COLUMN NOMBRE_CAMPO;

 /*  DML = LENGUAJE DE MANIPULACION DE DATOS   */
   --- INSERT   INSERTAR DATOS
            ***EJEMPLO INSERTAR DATOS***
            INSERT INTO fabricante VALUES(1, 'Asus');
            INSERT INTO fabricante VALUES(2, 'Lenovo');
            INSERT INTO fabricante VALUES(3, 'Hewlett-Packard');
            INSERT INTO fabricante VALUES(4, 'Samsung');
            INSERT INTO fabricante VALUES(5, 'Seagate');
            INSERT INTO fabricante VALUES(6, 'Crucial');
            INSERT INTO fabricante VALUES(7, 'Gigabyte');
            INSERT INTO fabricante VALUES(8, 'Huawei');
            INSERT INTO fabricante VALUES(9, 'Xiaomi');

            INSERT INTO producto VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
            INSERT INTO producto VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
            INSERT INTO producto VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
            INSERT INTO producto VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
            INSERT INTO producto VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
            INSERT INTO producto VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
            INSERT INTO producto VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
            INSERT INTO producto VALUES(8, 'Portátil Yoga 520', 559, 2);
            INSERT INTO producto VALUES(9, 'Portátil Ideapd 320', 444, 2);
            INSERT INTO producto VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
            INSERT INTO producto VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);
        - IMPORTAR ARCHIVO CSV
        - EXPORTAR ARCHIVO CSV
   --- UPDATE   ACTUALIZAR DATOS
        UPDATE NOMBRE_TABLE SET CAMPO_ACTUALIZAR='555555' WHERE CAMPO_ID=1
        UPDATE NOMBRE_TABLE SET CAMPO_ACTUALIZAR='555555' WHERE CAMPO_ID BETWEEN 1 AND 10
   --- DELETE   ELIMINAR DATOS
        DELETE FROM USUARIOS;
        DELETE FROM USUARIOS WHERE ID_CAMPO=25;
        DELETE FROM USUARIOS WHERE ID_CAMPO BETWEEN 10 AND 15
   --- SELECT   CONSULTAR REGISTRO DE DATOS
         -- WHERE IGUAL
         -- AND 
         -- OR
          ***EJEMPLO DE SINTAXYS***
            SELECT * FROM NOMBRE_TABLA 
            SELECT NOMBRE_CAMPO01,NOMBRE_CAMPO02 FROM NOMBRE_TABLA WHERE ID_CAMPO=10
            SELECT * FROM NOMBRE_TABLA WHERE NOMBRE_CAMPO=4444 
            SELECT * FROM NOMBRE_TABLA WHERE NOMBRE_CAMPO1='BERTA' AND NOMBRE_CAMPO02=29 
            SELECT * FROM NOMBRE_TABLA WHERE NOMBRE_CAMPO1='BERTA' OR NOMBRE_CAMPO02=29 
         -- >  MAYOR QUE 
          ***EJEMPLO DE SINTAXYS***
            SELECT * FROM NOMBRE_TABLA WHERE ID_CAMPO > 10  
         -- <  MENOR QUE
          ***EJEMPLO DE SINTAXYS***
            SELECT * FROM NOMBRE_TABLA WHERE ID_CAMPO < 10
         -- <= MENOR O IGUAL QUE
          ***EJEMPLO DE SINTAXYS***
            SELECT * FROM NOMBRE_TABLA WHERE ID_CAMPO <= 10
         -- >= MAYOR O IGUAL QUE
          ***EJEMPLO DE SINTAXYS***
            SELECT * FROM NOMBRE_TABLA WHERE ID_CAMPO >= 10
         -- <> !=  DIFERENTE  
          ***EJEMPLO DE SINTAXYS***
            SELECT * FROM NOMBRE_TABLA WHERE ID_CAMPO <> 10
         -- BETWEEN CAMPO01 AND CAMPO02
          ***EJEMPLO DE SINTAXYS***
            SELECT * FROM USUARIOS WHERE ID_CAMPO BETWEEN 10 AND 15
         -- LIKE 
           ***EJEMPLO DE SINTAXYS PARA BUSQUEDA QUE INICIE CON LA LETRA V ***
            SELECT * FROM USUARIOS WHERE CAMPO LIKE 'v%'       
           ***EJEMPLO DE SINTAXYS PARA BUSQUEDA QUE FINALICE CON LA LETRA V ***
            SELECT * FROM USUARIOS WHERE CAMPO LIKE '%v'
         -- IN
           ***EJEMPLO DE SINTAXYS OBTENEMOS LAS ID CON ESTOS PARAMETROS***
            SELECT * FROM CLIENTES WHERE ID_CLIENTE IN (1,2,3,4)
   --- FUNCIONES DE ORDENAMIENTO  ASCENDENTE O DESCENDENTE  
         -- ORDER BY , ASC  DESC
           ***EJEMPLO DE SINTAXYS ORDENAMINETO EN ASCENDENTE Y DESCENDENTE***
            SELECT * FROM NOMBRE_TABLA WHERE ID_CAMPO < 10 ORDER BY NOMBRE_CAMPO ASC
            SELECT * FROM NOMBRE_TABLA WHERE ID_CAMPO < 10 ORDER BY NOMBRE_CAMPO DESC
          
   --- FUNCIONES DE AGREGACIÓN 
         -- COUNT
           ***EJEMPLO DE SINTAXYS CONTABILIZA CANTIDAD DE NOMBRES CON FREDY ***
            SELECT COUNT (*) AS NOMBRE_CAMPO FROM NOMBRE_TABLA WHERE NOMBRE_CAMPO ='FREDY'
         -- SUM 
            ***EJEMPLO DE SINTAXYS SUMAMOS LAS EDADADES DE TODOS LOS FREDY ***
            SELECT SUM (*) AS NOMBRE_CAMPO FROM NOMBRE_TABLA WHERE NOMBRE_CAMPO ='FREDY' 
         -- MAX 
           ***EJEMPLO DE SINTAXYS OBTENEMOS EDAD MAXIMA ***
            SELECT MAX (EDAD) AS EDAD FROM NOMBRE_TABLA
         -- MIN 
           ***EJEMPLO DE SINTAXYS OBTENEMOS EDAD MINIMA ***
            SELECT MIN (EDAD) AS EDAD FROM NOMBRE_TABLA 
         -- AVG 
           ***EJEMPLO DE SINTAXYS OBTENEMOS EDAD MEDIA ***
            SELECT AVG (EDAD) AS EDAD FROM NOMBRE_TABLA       
         
         
   --- FUNCIONES DE AGRUPAMIENTO    
        GROUP BY
   --- UNIONES  
        INNER JOIN
        LEFT JOIN
        RIGHT JOIN      


 
 
/*OBTENER TODAS LAS COLUMNAS DE LA TABLA NOMBRE DE LA TABLA*/
SELECT * FROM NOMBRE_TABLA 
/*OBTENER EL USUARIO CON EL ID 2*/
/*OBTENER EL USUARIO CON EL EMAIL NOMBRE_EMAIL */
/*OBTENER TODOS LOS USUARIOS CON UNA EDAD MAYOR 25*/
/*OBTENER TODOS LOS USUARIOS CON UNA EDAD MENOR 50*/

/*OBTENER TODOS LOS USUARIOS QUE POSEA UNA BIOGRAFIA*/
/*OBTENER TODOS LOS USUARIOS QUE NO POSEA BIOGRAFIA*/

/*OBTENER TODOS LOS USUARIOS CUYA FECHA DE CREACION ES EL DIA DE HOY*/
/*OBTENER EL USERNAME DE TODOS LOS USUARIOS CUYO ID SE ENCUENTREN EN EL SIGUIENTE LISTADO
  [1,2,3,4]
 */
/*OBTENER LAS EDADES DE TODOS LOS USUARIOS MAYORES DE EDAD*/
/*OBTENER EL USERNAME Y CORREO ELECTRONICO DEL USUARIO CON MAYOR EDAD*/
/*OBTENER EL USERNAME Y CORREO ELECTRONICO DEL USUARIO CON MENOR EDAD*/
/*OBTENER EL USERNAME Y CORREO ELECTRONICO Y EDAD DE TODOS LOS USUARIOS CON RANGOS  DE EDAD ENTRE 20 Y 55 AÑOS*/ 
